### ISSUE TITLE
pdf preview not displayed

### ISSUE THREAD

**Issue by Mirage10** [Cubxity/typstudio#19]
Hello!

I am able to edit .typ file, but unfortunately  cannot see anything in pdfviewer. I am on manjaro archlinux 6.3

greetings

**Comment by Cubxity** [comment]
The file must be named main.typ, otherwise you have to specify the main file in project confit (GUI not yet implemented):

`.typstudio/project.json`
```json
{
  "main": "file.typ"
}
```

**Comment by Mirage10** [comment]
thumbs up! it works. wow very good the responsiveness of typstudio. would like to see mouse hover over command -> display examples -> insert examples ... just a dream ...
