### ISSUE TITLE
@local breaks live preview

### ISSUE THREAD

**Issue by omarsamir27** [Cubxity/typstudio#24]
@local is used for local packages, on linux this is ~/.local/share/typst/packages/local/{pkg-name}
the typst compiler correctly resolves the path and builds the pdf , but live preview does not work.

![image](https://github.com/Cubxity/typstudio/assets/39497615/07ddc711-aeb8-4cf2-9b90-b3eda1ddfb41)

**Comment by Cubxity** [comment]
Support for packages is not implemented yet. This is a bug.

**Comment by caoimhebyrne** [comment]
@omarsamir27 this was implemented in 12a2331.
![image](https://github.com/Cubxity/typstudio/assets/71222289/36a8c610-e8c8-4473-9159-6816a8c9871d)
