### ISSUE TITLE
Autocomplete panics on Windows on version v0.1.0-dev.24 and later

### ISSUE THREAD

**Issue by Enivex** [Cubxity/typstudio#26]
v0.1.0-dev.23 does work, so something was changed between these two builds

I do not know if logs are available anywhere, so I don't have any more information than this.

OS: Windows 11 23H2

**Comment by Cubxity** [comment]
Do you have the document in question?

**Comment by Enivex** [comment]
> Do you have the document in question?

It'll happen with anything. Even something with just plain text in it.

**Comment by Cubxity** [comment]
I'm unable to reproduce this issue with the latest build (AppImage) on Fedora 38 Workstation. Please provide debug logs if you're able to. Set the `RUST_LOG` environment variable to `debug`.

**Comment by Enivex** [comment]
> I'm unable to reproduce this issue with the latest build (AppImage) on Fedora 38 Workstation. Please provide debug logs if you're able to. Set the `RUST_LOG` environment variable to `debug`.

I would have to compile it myself in that case?

**Comment by Cubxity** [comment]
> > I'm unable to reproduce this issue with the latest build (AppImage) on Fedora 38 Workstation. Please provide debug logs if you're able to. Set the `RUST_LOG` environment variable to `debug`.
> 
> I would have to compile it myself in that case?

No. You should be able to run the compiled binary. I'm unsure how you would run the application with stdout on Windows, but I'm sure there's a way.

**Comment by Cubxity** [comment]
> @Enivex asked me to run it on Windows with `RUST_LOG="debug"` and attached are the logs from running with the following file: [out.log](https://github.com/Cubxity/typstudio/files/12396396/out.log)
> 
> ```ts
> #set page("a4")
> 
> = Hello, world!
> ```

Thank you. Seems like this may be a Windows-specific issue. Currently looking into it.

**Comment by Cubxity** [comment]
@Dherse could you try running the [fix/windows-autocomplete](https://github.com/Cubxity/typstudio/tree/fix/windows-autocomplete) branch?
