### ISSUE TITLE
Basic usage

### ISSUE THREAD

**Issue by fredguth** [Cubxity/typstudio#29]
I installed (macos) but when I open the app and try to open the folder icon it does not show any project and there is no menu or anything else to let me choose a folder. 

How should I proceed?

**Comment by caoimhebyrne** [comment]
@fredguth you have to use the "Open Project" action (or press CMD+O)
![image](https://github.com/Cubxity/typstudio/assets/71222289/341704a1-4a7d-4763-82dc-cd0443c42fbc)
