### ISSUE TITLE
Portable AMD64 (x86-64) binary Win11 download

### ISSUE THREAD

**Issue by humphreylee** [Cubxity/typstudio#4]
Please provide win_x86_64 binary zipped download. This is due to restriction (no admin) on my machine. Thanks.

**Comment by jlb6907** [comment]
+1 for me. Thanks.

**Comment by sitandr** [comment]
Tauri says nothing about exporting as portable, but extracting just the compiled .exe from src-tauri/target/release seems working for me. For now there are no additional resourses used, so there is only an .exe file.

Compiled on Windows 11 x64, so may be some incompatibility issues on other Windows versions. I know for sure that this will not work on Windows 7 without WebView installed.

[typstudio.zip](https://github.com/Cubxity/typstudio/files/11477310/typstudio.zip)

(This is no kind of official, just wanted to help. I hope that in future, when it will be stable, that will be automated with GithubActions for releases)

There is a bunch of web app functionality missing for now, but I think it is still cool for the start!

*P.S.* Feel free to ask for an update if still no official releases are present.

**Comment by humphreylee** [comment]
Thanks, the zip file of the download link is working. Is there more versatile solution rather this hard link? For example, to provide together with other download format

**Comment by sitandr** [comment]
Sorry, can you explain what exactly do you want to get? I'm not sure I understand your request. Again, I am, sadly, not connected to that project yet, so I can't provide a stable solution.

If you need to get regularly actual version of the build for different platforms, you can fork this repo and add Github actions for automated cross-platform building the way it is described on [Tauri website](https://tauri.app/v1/guides/building/cross-platform/).

**Comment by humphreylee** [comment]
Even though this is a "hack", but still a working solution. Thanks.
