### ISSUE TITLE
Windows build completely broken?

### ISSUE THREAD

**Issue by Enivex** [Cubxity/typstudio#5]
I downloaded the latest build, and the only thing I can do is "open project" to select a folder. The + on project then let's me create files (they show up in file explorer), but nothing actually shows up in the interface.

![image](https://user-images.githubusercontent.com/2191754/236780906-4555926b-75cf-462b-802f-0e5364acb7b2.png)

**Comment by Enivex** [comment]
I also tested the previous build, and that didn't work either

**Comment by Cubxity** [comment]
This seems to be an issue with the behavioral differences between Unix systems and Windows. I believe the issue lies within the path checking logic.

**Comment by Cubxity** [comment]
Fixed in https://github.com/Cubxity/typstudio/commit/58d39e358f7e9219a50c3edceaca88da9cc89a81
