### ISSUE TITLE
What is the expectent contents of the Edit & View menus?

### ISSUE THREAD

**Issue by alerque** [Cubxity/typstudio#7]
I've successfully built and packaged typstudio for Linux ([Arch Linux](https://aur.archlinux.org/packages/typstudio)), and most parts of it seem to work. I can open and edit files in a project and the compiler/preview works great.

I'm a bit confused though because the *Edit* & *View* menus have nothing at all in them, just a blank box (with about 8 lines but vary narrow) shows up.

This could be because nothing has been setup for them yet. I do understand this is at a pre-release stage, but with Tauri I would have at least expected copy/paste or something in the *Edit* menu.

Is there not supposed to be something there yet or is there a problem with my builds?

**Comment by Cubxity** [comment]
Nothing is supposed to be there yet at the moment. I have to implement the menu items manually, so it isn't implemented atm.

**Comment by alerque** [comment]
Fair enough, in that case I don't have to worry there is something wrong with my builds.
